on:
  workflow_dispatch:
  schedule:
  - cron: "0 1-23/2 * * *"
  push:
    branches:
    - main

jobs:
  update_page:
    name: Compile, run script, deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm ci --include=dev

      - name: Compile Typescript and Run update script
        env:
          BLIZZ_CLIENTID: ${{ secrets.BLIZZ_CLIENTID }}
          BLIZZ_SECRET: ${{ secrets.BLIZZ_SECRET }}
        run: |
          npm run generate

      - name: Build Resulting Site
        run : |
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build


