on:
  workflow_dispatch:
  schedule:
  - cron: "0 1-23/2 * * *"

jobs:
  update_page:
    name: Compile, run script, deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        env:
          BLIZZ_CLIENTID: ${{ secrets.BLIZZ_CLIENTID }}
          BLIZZ_SECRET: ${{ secrets.BLIZZ_SECRET }}
        run: |
      - name: Install dependencies
        run: |
          npm ci --include=dev

      - name: Compile Typescript and Run update script
        run: |
          npm run generate
        
      - name: Deploy Github Page
        run: |
          npm run deploy


